all::

prefix = $(HOME)
bindir = $(prefix)/bin
mandir = $(prefix)/share/man
man1dir = $(mandir)/man1

ASCIIDOC = asciidoc
INSTALL = install

-include config.mak

ifeq ($(V),)
QUIET_GEN =      @echo '      GEN $@';

export QUIET_GEN
endif

export mandir man1dir

DESTDIR_SQ = $(subst ','\'',$(DESTDIR))
bindir_SQ = $(subst ','\'',$(bindir))

git-integration: git-integration.sh
	$(QUIET_GEN)cp $^ $@

all:: git-integration

test: all
	$(MAKE) -C t

install: all
	$(INSTALL) -d -m 755 '$(DESTDIR_SQ)$(bindir_SQ)'
	$(INSTALL) -m 755 git-integration '$(DESTDIR_SQ)$(bindir_SQ)'

doc man html:
	$(MAKE) -C Documentation/ $@

install-doc:
	$(MAKE) -C Documentation/ install

.PHONY: all test install install-doc doc man html


gh-pages:
	$(QUIET_GEN)rm -rf gh-pages && \
	GIT_INDEX_FILE=.git/gh-pages.index && \
	export GIT_INDEX_FILE && \
	git read-tree gh-pages && \
	git checkout-index --prefix=gh-pages/ --all && \
	$(ASCIIDOC) --conf Documentation/site.asciidoc.conf -b html5 \
		--out-file=gh-pages/index.html Documentation/index.txt && \
	blob=$$(git hash-object -w gh-pages/index.html) && \
	git update-index --add --cacheinfo 100644 $$blob index.html && \
	oldtree=$$(git rev-parse --verify gh-pages^{tree}) && \
	tree=$$(git write-tree) && \
	( \
		test $$oldtree = $$tree || { \
		commit=$$(git commit-tree $$tree -p gh-pages \
			-m "Autogenerated site for $$(git describe --always HEAD)") && \
		git update-ref refs/heads/gh-pages $$commit; } \
	)

.PHONY: gh-pages
